name: AES Aben
authors: Darcy Manoel
homepage: https://github.com/Adde-Endless-Sky/Aben
license: GPL-3.0-or-later
version: c55404b7917273953fb28c059b33f7841c31cb09
shortDescription: Fills in space in the galaxy with a new alien species.
description: New aliens that are incapable of spaceflight as far as the player is
  concerned, offers the player multiple missions in aiding the Aben which also benefit
  the player in turn.
url: https://github.com/Adde-Endless-Sky/Aben/archive/c55404b7917273953fb28c059b33f7841c31cb09.zip
iconUrl: https://github.com/Adde-Endless-Sky/Aben/raw/c55404b7917273953fb28c059b33f7841c31cb09/icon.png
autoupdate:
  type: commit
  branch: main
  url: https://github.com/Adde-Endless-Sky/Aben/archive/$version.zip
  iconUrl: https://github.com/Adde-Endless-Sky/Aben/raw/$version/icon.png
